### ISSUE TITLE
Parse multiple cards in one file

### ISSUE THREAD

**Issue by gaetgu** [riboseinc/ruby-vobject#10]
Hello, thanks for creating this gem!

I was playing around with it and I noticed that if I used multiple VCards in one file, it would throw an error.
I have several (more than a hundred) VCards and I really don't want to create an individual file for each VCard, so is there any way to just parse them all in one file? Thanks a lot!

Error output:

```ruby
/usr/local/lib/ruby/gems/2.7.0/gems/ruby-vobject-1.0.1/lib/vobject/vcard/v3_0/grammar.rb:156:in `parse':  (Rsec::SyntaxError)
in source:9 at 1
BEGIN:VCARD
 ^
	from /usr/local/lib/ruby/gems/2.7.0/gems/ruby-vobject-1.0.1/lib/vobject/vcard/v3_0/component.rb:10:in `parse'
	from /usr/local/lib/ruby/gems/2.7.0/gems/ruby-vobject-1.0.1/lib/vcard.rb:18:in `parse'
	from /Users/gabriel/Downloads/ruby-vobject-master/main.rb:9:in `<main>'
```

**Comment by ronaldtse** [comment]
Thanks @gaetgu for the feedback! 

@skalee @abunashir do you have a bit of time for this? Thanks!

**Comment by skalee** [comment]
@ronaldtse Note that if have to change types of some return values (object -> array of objects), this will be a breaking change.

**Comment by ronaldtse** [comment]
New method that allows parsing 1 (card) vs 1 (collection of cards)?

**Comment by skalee** [comment]
Hmm, yes, that will do the trick.

Also I wonder if:

- vCards 3.0 can be mixed with vCards 4.0 in one file
- vCards and iCalendars can be mixed in one file

I suppose the answer "yes if it is reasonably doable", but I don't know if these are real-life cases. Especially mixing VCard and iCalendar files — although I can imagine that from technical point of view, this is not defined in the standards, and these formats are expected to use different MIME types.

**Comment by ronaldtse** [comment]
Technically they are acceptable, because the vCard/iCalendar specifications do not actually specify what it means to be a collection.
