### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by skalee** [riboseinc/ruby-vobject#16]
> Successfully run specs for Ubuntu and MacOS. Windows specs are the same as before: they fail as on master

_Originally posted by @alexeymorozov in https://github.com/riboseinc/ruby-vobject/pull/13#issuecomment-669216812_

It seems to have problems with parsing time zones. Perhaps information on them is missing?

Two failures from https://github.com/riboseinc/ruby-vobject/runs/949560720:

```
   1) Vobject should process RFC6868 caret parameters
      Failure/Error: expect(vobj_json).to include_json(exp_json)
 
                  json atom at path "VCALENDAR/VTIMEZONE/STANDARD/DTSTART/value/zone" is not equal to expected value:
 
                    expected: "America/Los_Angeles"
                         got: ""
                  
                  json atom at path "VCALENDAR/VTIMEZONE/DAYLIGHT/DTSTART/value/zone" is not equal to expected value:
 
                    expected: "America/Los_Angeles"
                         got: ""
                  
                  json atom at path "VCALENDAR/VEVENT/DTSTART/value/zone" is not equal to expected value:
 
                    expected: "America/Los_Angeles"
                         got: ""
                  
                  json atom at path "VCALENDAR/VEVENT/DTEND/value/zone" is not equal to expected value:
 
                    expected: "America/Los_Angeles"
                         got: ""
                  
      # ./spec/vobject_spec.rb:34:in `block (2 levels) in <top (required)>'
```

```
   16) Vobject should parse iCalendar properly with RECUR instances
       Failure/Error: tz = TZInfo::Timezone.get(params[:TZID])
 
       TZInfo::DataSourceNotFound:
         No source of timezone data could be found.
         Please refer to https://tzinfo.github.io/datasourcenotfound for help resolving this error.
       # ./vendor/bundle/ruby/2.6.0/gems/tzinfo-2.0.2/lib/tzinfo/data_source.rb:159:in `rescue in create_default_data_source'
       # ./vendor/bundle/ruby/2.6.0/gems/tzinfo-2.0.2/lib/tzinfo/data_source.rb:156:in `create_default_data_source'
       # ./vendor/bundle/ruby/2.6.0/gems/tzinfo-2.0.2/lib/tzinfo/data_source.rb:55:in `block in get'
       # ./vendor/bundle/ruby/2.6.0/gems/tzinfo-2.0.2/lib/tzinfo/data_source.rb:54:in `synchronize'
       # ./vendor/bundle/ruby/2.6.0/gems/tzinfo-2.0.2/lib/tzinfo/data_source.rb:54:in `get'
       # ./vendor/bundle/ruby/2.6.0/gems/tzinfo-2.0.2/lib/tzinfo/timezone.rb:235:in `data_source'
       # ./vendor/bundle/ruby/2.6.0/gems/tzinfo-2.0.2/lib/tzinfo/timezone.rb:128:in `get'
       # ./lib/vobject/vcalendar/typegrammars.rb:477:in `typematch'
       # ./lib/vobject/vcalendar/grammar.rb:292:in `block in vobject_grammar'
       # ./vendor/bundle/ruby/2.6.0/gems/rsec-1.0.0/lib/rsec/parsers/misc.rb:8:in `_parse'
       # ./vendor/bundle/ruby/2.6.0/gems/rsec-1.0.0/lib/rsec/parsers/misc.rb:79:in `block in _parse'

       # < a very long stack trace was here >

       # ./vendor/bundle/ruby/2.6.0/gems/rsec-1.0.0/lib/rsec/parsers/seq.rb:7:in `_parse'
       # ./vendor/bundle/ruby/2.6.0/gems/rsec-1.0.0/lib/rsec/parsers/misc.rb:6:in `_parse'
       # ./vendor/bundle/ruby/2.6.0/gems/rsec-1.0.0/lib/rsec/parsers/misc.rb:120:in `_parse'
       # ./lib/vobject/vcalendar/grammar.rb:576:in `parse'
       # ./lib/vobject/vcalendar/component.rb:11:in `parse'
       # ./lib/vcalendar.rb:12:in `parse'
       # ./spec/vobject_spec.rb:636:in `block (2 levels) in <top (required)>'
       # ------------------
       # --- Caused by: ---
       # TZInfo::DataSources::ZoneinfoDirectoryNotFound:
       #   None of the paths included in TZInfo::DataSources::ZoneinfoDataSource.search_path are valid zoneinfo directories.
       #   ./vendor/bundle/ruby/2.6.0/gems/tzinfo-2.0.2/lib/tzinfo/data_sources/zoneinfo_data_source.rb:232:in `initialize'
```

**Comment by skalee** [comment]
Sorry, my bad. It's a duplicate of https://github.com/riboseinc/ruby-vobject/issues/14, and fixed already.
